version: '3.8'

services:
  next-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://your-production-domain/api
    command: yarn start
