import type { Metadata } from "next";
import "./globals.css";
import SiteHeader from "../components/site-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-svh bg-background font-sans antialiased"
      >
      <SiteHeader />
        {children}
      </body>
    </html>
  );
}
