name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg NODE_ENV=production -t ${{ secrets.DOCKER_USERNAME }}/next-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/next-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/next-app:latest
            docker stop next-app || true
            docker rm next-app || true
            docker run -d --name next-app \
            -p 80:3000 \
            -e NODE_ENV=production \
            -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            ${{ secrets.DOCKER_USERNAME }}/next-app:latest
